### ISSUE TITLE
Installation on Ubuntu 16.04

### ISSUE THREAD

**Issue by aydeger** [dlinknctu/OpenNet#100]
![screenshot from 2016-08-30 04-32-36](https://cloud.githubusercontent.com/assets/7677480/18066485/33b682e0-6e6b-11e6-8762-216bc8c0a04d.png)
I am trying to install Opennet with given instructions on my virtual machine installed Ubuntu 16.04. I got the error at the figure. Anyone knows whether it is not supporting Ubuntu 16.04 or another reason causes to problem?
Beginning of error:
TASK [gccxml : make gccxml] ****************************************************
fatal: [master]: FAILED!

**Comment by kansokusha** [comment]
Hi, that is a known issue.
Since gcc version on Ubuntu 16.04 is 5.1, build gccxml on Ubuntu 16.04 will fail.
So, we suggest to build OpenNet on Ubuntu 14.04.

In future release, we may upgrade to Ubuntu 16.04, but release date is to be determined.
Reference: [(Bug 2451)] (https://www.nsnam.org/bugzilla/show_bug.cgi?id=2451)

**Comment by aydeger** [comment]
I installed 14.04 on new VM and got this error:
![screenshot from 2016-08-31 01 18 57](https://cloud.githubusercontent.com/assets/7677480/18099407/fd9cca58-6f18-11e6-9b1c-4184ffd1d97f.png)
Error starts after: TASK [openvswitch : Install OpenvSwitch debian packages] ***********************

**Comment by kansokusha** [comment]
Hi, I have installed a new Ubuntu VM and built OpenNet.
But does not encounter this problem.
The version of ansible on this VM is 2.1.1.0.

![build_opennet](https://cloud.githubusercontent.com/assets/2024544/18194873/31a471da-711b-11e6-81e3-8be82c2d8def.PNG)

**Comment by elveera0491** [comment]
![image](https://cloud.githubusercontent.com/assets/26124681/24066306/a0e473f8-0b47-11e7-935f-0fe4ced1aa3c.png)

I tried installing OpenNet on Ubuntu 14.04 VM but I encountered the issue mentioned by aydeger. Your tutorial says that there is an mininet directory as well. I dont see any mininet directory. Please help! Thank you in advance!

**Comment by kansokusha** [comment]
Hi, elveera0491, the [tutorial](https://github.com/dlinknctu/OpenNet/blob/master/doc/TUTORIAL.md#opennet-directories) is talking about installed OpenNet.
You can try to [build](https://github.com/dlinknctu/OpenNet#build-opennet) OpenNet on your Ubuntu 14.04.

**Comment by elveera0491** [comment]
I tried to build as well but it failed in Ubuntu 14.04 in the same way as mentioned by 'aydeger' above. Can you help me with this?

**Comment by elveera0491** [comment]
The following screenshot shows the error i encountered. I tried the build on Ubuntu 14.04.5.

![image](https://cloud.githubusercontent.com/assets/26124681/24073082/d99fa0fc-0bc7-11e7-9191-55865e201b5c.png)

**Comment by kansokusha** [comment]
The error shall be a network issue, the installation has failed to execute 'apt-get update'.
Retry install.sh in stable network environment may avoid this issue.

**Comment by elveera0491** [comment]
Sorry to bother you. Is it necessary to pre-install mininet and ns3 before executing the commands in the build? 

Thank you so much for your time and help!

P.S.: ns3 takes a lot of time for installation.

**Comment by kansokusha** [comment]
Hi elveera0491, OpenNet needs customized mininet and NS-3, so pre-install them may be not a good option. During the installation, OpenNet will apply some patches on mininet and NS-3 automatically.

Give the environment more resource will speed up the installation, like 2GB RAM, 2 CPU core, etc.

Sorry for that we do not have a person-in-charge to reply issues for now, only rely on voluntarily response from OpenNet team member.

**Comment by elveera0491** [comment]
Hi, I have tried a couple of times but it doesn't work for me. Is there a work around for this? Thank you so much for all the help.

**Comment by elveera0491** [comment]
Hey @kansokusha. I tried installing OpenNet again and it worked this time! Thank you so much for your time.
![image](https://cloud.githubusercontent.com/assets/26124681/25065800/cb3f866c-21e3-11e7-9840-251d9f39e1b9.png)

**Comment by kansokusha** [comment]
Congratulation and thank you for your notification.
