### ISSUE TITLE
OXM match fields missing

### ISSUE THREAD

**Issue by MichalPalatinus** [dlinknctu/OpenNet#105]
Hi, 
I am using OpenNet with Ryu controller and the packets I receive at controller have only 'in_port' in oxm_fields. There is no information about ether_type or any other protocols as it is common to in OF1.3.
Never happened to me before, so I don't know if its OpenNet issue or the problem is somewhere else.
Do you have any suggestions?

Thank you

Michal

**Comment by rascov** [comment]
It is unlikely to be an OpenNet issue since the OF protocol of OpenNet is handled by OVS, which is an mature solution in terms of OF 1.3 support.
Does the situation persist if you connect one OVS directly to the controller?

**Comment by MichalPalatinus** [comment]
Never mind, dumb question :D
