### ISSUE TITLE
Some problem with wifi module

### ISSUE THREAD

**Issue by sjtutyx** [dlinknctu/OpenNet#116]
Actually, I am now trying to run the OpenNet wifi module in my computer.
The example I am now trying to run is:
wifi-adhoc.py(some code attached)
~~~~
h0 = net.addHost( 'h0' )
h1 = net.addHost( 'h1' )
h2 = net.addHost( 'h2' )
wifi = WIFISegment()
wifi.addAdhoc( h0 )
wifi.addAdhoc( h1 )
wifi.addAdhoc( h2 )
~~~~
However, I cannot ping from h0 to h1, either h0 to h2,(error: unknown host h1)
So what's the problem? Is there any file I lost?  
Many thanks!

**Comment by sjtutyx** [comment]
When I try to use Xterm to run h0 h1 h2, the ping function give us the error: network is unreachable.
I am so sorry about that.

**Comment by kansokusha** [comment]
Hi, please refer [reading material](https://github.com/dlinknctu/OpenNet#reading-material).
Since we can not judge the status of your emulation, please collect more info and use knowledge from reading material, then you can find out what happens and resolve issues.

**Comment by sjtutyx** [comment]
Thanks~
