### ISSUE TITLE
How to implement the wifi network in real world

### ISSUE THREAD

**Issue by matrix69** [dlinknctu/OpenNet#117]
Hi
I wanted to implement the same network that is implemented in the paper in real world. I wanted to ask if you have any idea how to do that and what are the required hardwares?
Is there any SDN-enabled access point?
or, should I connect an AP to a SDN-switch?
or, should I use any programmable AP?
or, should I use an SDN-switch and attach a radio antenna to it?
I will really appreciate your help.

thank you very much

**Comment by kansokusha** [comment]
Hi, you may be interested in OpenWRT.
That is an OS which can be installed on AP and have OpenvSwitch software package.

**Comment by matrix69** [comment]
thank you very much!
