### ISSUE TITLE
Installing OpenNet : Task [ pygccxml : Download pygccxml ]

### ISSUE THREAD

**Issue by seawood** [dlinknctu/OpenNet#135]
Hi everyone,
 I tried to install OpenNet on Ubuntu 14.04.1 and problem occurred:

-------------------

TASK [pygccxml : Download pygccxml] ********************************************
fatal: [master]: FAILED! => {"changed": false, "dest": "/tmp", "failed": true, "gid": 0, "group": "root", "mode": "01777", "msg": "Connection failure: [Errno 104] 连接被对方重设", "owner": "root", "size": 4096, "state": "directory", "uid": 0, "url": "http://nchc.dl.sourceforge.net/project/pygccxml/pygccxml/pygccxml-1.0/pygccxml-1.0.0.zip"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/root/OpenNet/ansible/playbook.retry

PLAY RECAP *********************************************************************
master                     : ok=37   changed=21   unreachable=0    failed=1 

-----------------
Please help me !

**Comment by pichuang** [comment]
Hi Seawood,

Please replace the url to `https://excellmedia.dl.sourceforge.net/project/pygccxml/pygccxml/pygccxml-1.0/pygccxml-1.0.0.zip` or download it manually.

Thanks.

**Comment by seawood** [comment]
Hi Pichuang,

I can't find where the original URL is. So I tried the second solution.
I download it manually and put it int the OpenNet directory. But the same problem still occurred.

**Comment by seawood** [comment]
Thank you Pichuang,

Download it manually and put it into the /tmp directory.
Or Replace the url in the ~/OpenNet/ansible/roles/pygccxml/tasks/main.yml file.
