### ISSUE TITLE
Can you have more material tips for me to study and how I view the animation?

### ISSUE THREAD

**Issue by brunoguedessp** [dlinknctu/OpenNet#25]
I installed the VM and the example ran perfectly. I'm new to SDN and read your article. I would be very grateful if you could me to indicate more materials that allow me to create more experiments with the OpenNet. If you can, please tell me how to view the experiment with NetAnim. Thank U

**Comment by kansokusha** [comment]
We are going to add NetAnim related instructions.
You can find more examples with the link in the Reference section.

**Comment by rascov** [comment]
The instruction of viewing the animation has been merged to the master branch hence I am closing this issue. 
You can find it in the 'Run NetAnim' section in the README.

Please let us know if you still have problem.
