### ISSUE TITLE
Upgrade patches for ns-3.21

### ISSUE THREAD

**Issue by senthilkuma** [dlinknctu/OpenNet#3]
Hello,

i try to connect mininet with NS3 and i have followed steps but when i try to install OpenNet i get problems.

after applying patches to the NS3 original file it shows error and patch file also not success in some modules

i got these error

[ 844/1790] cxx: scratch/first.cc -> build/scratch/first.cc.3.o
[ 845/1790] cxx: scratch/third.cc -> build/scratch/third.cc.2.o
[ 888/1790] cxx: src/wifi/model/sta-wifi-mac.cc -> build/src/wifi/model/sta-wifi-mac.cc.1.o
../src/wifi/model/sta-wifi-mac.cc: In member function ‘void ns3::StaWifiMac::SetupStaMacListener(ns3::Ptr<ns3::WifiPhy>)’:
../src/wifi/model/sta-wifi-mac.cc:761:52: error: cannot allocate an object of abstract type ‘ns3::PhyStaMacListener’
../src/wifi/model/sta-wifi-mac.cc:63:7: note:   because the following virtual functions are pure within ‘ns3::PhyStaMacListener’:
./ns3/wifi-phy.h:84:16: note:   virtual void ns3::WifiPhyListener::NotifyTxStart(ns3::Time, double)
./ns3/wifi-phy.h:113:16: note:  virtual void ns3::WifiPhyListener::NotifySleep()
./ns3/wifi-phy.h:117:16: note:  virtual void ns3::WifiPhyListener::NotifyWakeup()
Waf: Leaving directory `/home/ubuntu/tarballs/ns-allinone-3.21/ns-3.21/build'
Build failed
 -> task in 'ns3-wifi' failed (exit status 1):
        {task 47926992: cxx sta-wifi-mac.cc -> sta-wifi-mac.cc.1.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-I.', '-I..', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_SQLITE3=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_GSL=1', '../src/wifi/model/sta-wifi-mac.cc', '-c', '-o', 'src/wifi/model/sta-wifi-mac.cc.1.o']

**Comment by rascov** [comment]
We have announced a new version for ns-3.21.
Please follow the new instruction with the new version of ns-3 and mininet.
These issue should be fixed in the new release.
If you still have some trouble. Please open another issue. Thanks.

**Comment by senthilkuma** [comment]
Thank you sir.. I will try now ..

**Comment by senthilkuma** [comment]
hello sir,

can i ask onething?  it will work with Ubuntu or Fedora?

**Comment by rascov** [comment]
Fedora only for now.

**Comment by senthilkuma** [comment]
Ok sir..Thnks..

**Comment by Jean7** [comment]
Hello
Someone know how I could overcome the following erro?

Build failed
 -> task in 'ns3-wifi' failed (exit status 1): 
	{task 139842736147792: cxx sta-wifi-mac.cc -> sta-wifi-mac.cc.1.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-I.', '-I..', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_SQLITE3=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_GSL=1', '../src/wifi/model/sta-wifi-mac.cc', '-c', '-o', 'src/wifi/model/sta-wifi-mac.cc.1.o']
 -> task in 'ns3-wifi' failed (exit status 1): 
	{task 139842736145872: cxx mac-low.cc -> mac-low.cc.1.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-I.', '-I..', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_SQLITE3=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_GSL=1', '../src/wifi/model/mac-low.cc', '-c', '-o', 'src/wifi/model/mac-low.cc.1.o']

It's important to mention that I use ns-3.22 release.

Thanks,

**Comment by kansokusha** [comment]
Hello, could you please use install.sh to build the environment?
Our patch has not yet support ns-3.22.

**Comment by nasrin-seifi** [comment]
Hi,
Could you do me a favor? I'm beginner in ns3 and opennet, first i read tutorial and step by step installed every requirements after that by using tarball downloaded and build and configure ns3.25.
when bind pygccxml, I receive this message:

mininet@ubuntu:~/ns-allinone-3.25/ns-3.25$ ./waf --pyrun examples/wireless/mixed-wireless.py
Waf: Entering directory `/home/mininet/ns-allinone-3.25/ns-3.25/build'
[ 296/1851] Processing command (${PYTHON}): ../bindings/python/ns3modulegen-modular.py ../src/internet/bindings/modulegen__gcc_ILP32.py -> src/internet/bindings/ns3module.cc src/internet/bindings/ns3module.h src/internet/bindings/ns3modulegen.log

Waf: Leaving directory `/home/mininet/ns-allinone-3.25/ns-3.25/build'
Build failed
 -> task in 'pybindgen(ns3 module internet)' failed (exit status 1): 
	{task 3064338124L: command_task ns3modulegen-modular.py,modulegen__gcc_ILP32.py -> ns3module.cc,ns3module.h,ns3modulegen.log}
''

when I use opennet again there is problem:

root@ubuntu:~/OpenNet/mininet-patch/examples/opennet# python wifiroaming.py 
Traceback (most recent call last):
  File "wifiroaming.py", line 14, in <module>
    import mininet.ns3
  File "build/bdist.linux-i686/egg/mininet/ns3.py", line 40, in <module>
ImportError: No module named ns.core

"mininet" and after that "mininet-ns3 integration" was installed.

Thanks in advance.

**Comment by eronad** [comment]
I am having the same issue with the ns-3.25. I have installed OpenFlow module and it was configured and built successfully. I then decided to patch the mobility file, so I had to go to the upper folder, which is ns-allinone-3.25, and run ./build.py --enable-examples --enable-tests; however, the build failed and the following error is what has been encountered. 
Waf: Leaving directory `/home/nadir/workspace/ns-allinone-3.25/ns-3.25/build'
Build failed
 -> task in 'ns3-wifi' failed (exit status 1): 
	{task 140149717723280: cxx sta-wifi-mac.cc -> sta-wifi-mac.cc.1.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-I.', '-I..', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_GSL=1', '-DHAVE_SQLITE3=1', '../src/wifi/model/sta-wifi-mac.cc', '-c', '-o', '/home/nadir/workspace/ns-allinone-3.25/ns-3.25/build/src/wifi/model/sta-wifi-mac.cc.1.o']
Traceback (most recent call last):
  File "./build.py", line 171, in <module>
    sys.exit(main(sys.argv))
  File "./build.py", line 162, in main
    build_ns3(config, build_examples, build_tests, args, build_options)
  File "./build.py", line 82, in build_ns3
    run_command([sys.executable, "waf", "build"] + build_options)
  File "/home/nadir/workspace/ns-allinone-3.25/util.py", line 25, in run_command
    raise CommandError("Command %r exited with code %i" % (argv, retval))
util.CommandError: Command ['/usr/bin/python', 'waf', 'build'] exited with code 1


I would appreciate if any of you give me a helping hand to overcome this error.

**Comment by SorraFatima** [comment]
Hello everyone I am trying to run my first.cc file in ns3.27 but below is the following error it gives me.
Build failed
 -> task in 'third' failed (exit status 1): 
	{task 3071236780L: cxx third.cc -> third.cc.4.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-std=c++11', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-pthread', '-I.', '-I..', '-I/usr/include/libxml2', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_LIBXML2=1', '../examples/tutorial/third.cc', '-c', '-o', '/home/fatimah/Desktop/ns-allinone-3.27/ns-3.27/build/examples/tutorial/third.cc.4.o']
can anyone please help?

**Comment by pichuang** [comment]
@SorraFatima 
1. Suggest to split the issue to another
2. The information is not enough for me to troubleshooting.
