### ISSUE TITLE
Problems installing OpenNet

### ISSUE THREAD

**Issue by senthilkuma** [dlinknctu/OpenNet#4]
Hello sir,

i need one help when i run OpenNet i got some problems regarding NS3.py it shows error like this
can you help me to solve this issues?

senthil@ubuntu:~/ns/ns-allinone-3.18.1/ns-3.18.1$ sudo ./waf --pyrun /home/senthil/mininet-ns3-integration/examples/wifiroaming.py
Waf: Entering directory `/home/senthil/ns/ns-allinone-3.18.1/ns-3.18.1/build'
Waf: Leaving directory `/home/senthil/ns/ns-allinone-3.18.1/ns-3.18.1/build'
'build' finished successfully (1.125s)

Modules built:
antenna                   aodv                      applications             
bridge                    buildings                 config-store             
core                      csma                      csma-layout              
dsdv                      dsr                       emu                      
energy                    fd-net-device             flow-monitor             
internet                  lte                       mesh                     
mobility                  mpi                       netanim                  
network                   nix-vector-routing        olsr                     
point-to-point            point-to-point-layout     propagation              
spectrum                  stats                     tap-bridge               
test (no Python)          topology-read             uan                      
virtual-net-device        visualizer                wifi                     
wimax                    

Modules not built (see ns-3 tutorial for explanation):
brite                     click                     openflow                 

*** Adding controller
ip tuntap add h1-eth0 mod tap
Traceback (most recent call last):
  File "/home/senthil/mininet-ns3-integration/examples/wifiroaming.py", line 154, in <module>
    WifiNet()
  File "/home/senthil/mininet-ns3-integration/examples/wifiroaming.py", line 119, in WifiNet
    tb = addfunc (node, wichannel, wissid)
  File "build/bdist.linux-x86_64/egg/mininet/ns3.py", line 502, in addSta
    
AttributeError: type object 'wifi.StaWifiMac' has no attribute 'ACTIVE'
Command ['/usr/bin/python', '/home/senthil/mininet-ns3-integration/examples/wifiroaming.py'] exited with code 1

**Comment by rascov** [comment]
We have announced a new version for ns-3.21.
Please follow the new instruction with the new version of ns-3 and mininet.
These issue should be fixed in the new release.
If you still have some trouble. Please open another issue. Thanks.

**Comment by senthilkuma** [comment]
hello Prof,

I have used your Vm image for OpenNet, and it works fine.. 
now i have few questions about OpenNet

1. do you have any ideas or example script for to use Mininet openflow with ns3 LTE networks?
because i want to use mininet openflow function with NS3 LTE module

**Comment by rascov** [comment]
Hi,

We are not working with LTE.
However, from most of the cases I have heard, the LTE BS are connected to
OpenFlow-enabled switches, rather than support OpenFlow itself.
In that case, I guess you can create a LTE BS in ns-3 and connect it to the
switches in ns-3.

**Comment by senthilkuma** [comment]
Ok sir Thank you..

**Comment by senthilkuma** [comment]
Hello sir,

I have some problem to run OpenNet.
i am using opennet vm image

as your instruction i have followed

first i put controller command like this

"sudo python pox.py forwarding.l2_learning"

and i open another vm and put this command

"sudo ./waf shell"   it goes to root

and i put this command

"sudo python wifiroaming.py"

but it shows error like this

traceback (most recent call last)
file "wifiroaming.py" line 14, <in module>
import mininet.ns3
File  "/build/bdist.linux-x86_64/egg/mininet/ns3.py", line 40, <in module>
Import Error : No module names ns.core

can you help me sir? Actually first time i tried it works but after some time it doesn't work

**Comment by kansokusha** [comment]
Thank you for report this issue, we gave a wrong command in that section.
After "sudo ./waf shell", the following command "sudo python wifiroaming.py" should not contains "sudo".
Just type "python wifiroaming.py", it should works.

**Comment by senthilkuma** [comment]
Yes sir, it works.. Thank you so much..

**Comment by senthilkuma** [comment]
Hello sir,

I need one help 
do you have any documentation about "how to use mininet openflow switch and controller into ns3"
can you give some ideas?

**Comment by kansokusha** [comment]
Sorry, we don't have documentation about how to use yet.
While Mininet takes its node as usual OpenFlow node, here embed nsNode for ns3 properties into Mininet node.
OpenFlow may not can directly provide the operation of wireless properties. 
Since the OpenFlow is mainly designed to manage the flow table.

**Comment by senthilkuma** [comment]
Ok sir i got it..

**Comment by senthilkuma** [comment]
Hello sir,

i heard OpenNet now support Ubuntu 14.04.1.. so what is the instruction for install opennet in ubuntu 14.04.1?

**Comment by rascov** [comment]
Please find the instruction in the README.
