### ISSUE TITLE
NetAnim Error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by brunoguedessp** [dlinknctu/OpenNet#59]
Hi,

I would like to see the NetAnim working, but when I try to open the simulation's file (/tmp/xlm/wifi-wired-bridged4.xml) the error above happens. Do you have any idea how to solve that?

**Comment by kansokusha** [comment]
Please try latest master branch, NetAnim shall work.
Using install.sh is the most recommended way to setup the environment of OpenNet.

**Comment by brunoguedessp** [comment]
So... the OpenNet VM image is not the best way to run the experiments? You mean I should install a CenTOS, Fedora or Ubuntu machine and to use install.sh script?

**Comment by kansokusha** [comment]
Yes, the most used combination among our staff is the script and Ubuntu.
We will revise the README and remove out-of-date information.
