### ISSUE TITLE
issue with the qmake-qt4 

### ISSUE THREAD

**Issue by Jendorski** [dlinknctu/OpenNet#61]
I input the qmake-qt4 (or qmake NetAnim.pro), only to obtain syntax error in token '('. 
Please help.
Thanks

**Comment by kansokusha** [comment]
Hi,

Type "qmake-qt4 NetAnim.pro" shall enough to build the NetAnim, "qmake NetAnim.pro" is an alternative option.
Currently the VM image has some issues, we will update the install instruction in  README and suspend the support of VM image.
