### ISSUE TITLE
Bluetooth implementation

### ISSUE THREAD

**Issue by matrix69** [dlinknctu/OpenNet#65]
Hi, 
I want to implement a blootooth netwrok working with SDN controller, Can I use OpenNet to implement it? how should I change OpenNet for that purpose?
thank you

**Comment by pichuang** [comment]
Hi,
I'm not sure whether ns3 implement functions about bluetooth. if you want to implement, try to read ns3 document.

**Comment by matrix69** [comment]
Alright, thank you.

**Comment by matrix69** [comment]
Hi 
I find out that NS3 has not implement it yet, but NS2 does. so as experts said I need to port it form NS2 into NS3. I dont know what it means and how should I do it. 
I have questions. can I change the some parts of NS3 in OpenNet? How Should I do this? Doesn't it change any thing? should I change any thing in OpenNet files? are NS3 codes flexible in OpenNet? I mean Is there NS3 source code in OpenNet? how should I compile NS3 within OpenNet. I am just confused can you guide me please.

thank you

**Comment by kansokusha** [comment]
The NS-2 Bluetooth extension does not compatible with NS-3.
"Port" means manually translate the code of NS-2 Bluetooth extension into NS-3 modules.
[NS-2 Bluetooth extension - UCBT](http://eecs.ceas.uc.edu/~cdmc/ucbt/)
[High Speed Bluetooth NS2 Simulation Model - HSBT](https://code.google.com/p/hsbt/)

OpenNet contains NS-3 source codes, and the NS-3 part can be built independently.
If you need to add extra features to NS-3, just modify NS-3 codes and use the waf to build NS-3 again.
NS-3 provides detailed documents about how to use it and build it.
The following references may be helpful.
[Building NS-3 with waf] (https://www.nsnam.org/docs/release/3.24/tutorial/html/getting-started.html#building-with-waf)
[NS-3 tutorial](https://www.nsnam.org/docs/release/3.24/tutorial/html/index.html)

**Comment by matrix69** [comment]
Thanks a lot. I start implementation.
