### ISSUE TITLE
Host unreachable problem in wifiroaming.py example

### ISSUE THREAD

**Issue by Ehwaz** [dlinknctu/OpenNet#7]
I succeeded to install OpenNet and run wifiroaming.py example,
but "ping 10.0.0.2 -c 100" in the example fails; It says h1 can not reach h2.
(In stdout, message "From 10.0.0.1 icmp_seq=7 Destination Host Unreachable" is printed)

I installed OpenNet through following procedures.
1) I got Virtualbox VM from this [link](https://github.com/mininet/mininet/wiki/Link-modeling-using-ns-3#midterm).
2) In above VM there is ns-3.17, so I downloaded ns-3.18.1 source and built it. (I refered Issue #3)
3) I applied patches in OpenNet, except 'tap-bridge-offset.patch'; I used [this file](https://www.nsnam.org/bugzilla/attachment.cgi?id=1750) instead. (Also refered Issue #3)
4) I installed patched minint by running 'sudo mininiet/util/install.sh'.
5) I ran following commands in ns-3 directory.
Errors occured during './waf --apiscan=netanim', so I installed gcc-4.7-multilib, g++-4.7-multilib and pygccxml.
```
./waf -d optimized --enable-sudo configure
./waf --apiscan=netanim
./waf build
```
6) There was an error that prototype of TabBridge::Filter() is different in ../src/tap-bridge/model/tap-bridge.cc and tap-bridge.hh, so I fixed it to the one in tap-bridge.cc.
7) I tried to run wifiroaming.py, but there was an error that mininet can't catch 'ns.wifi.StaWifiMac.ACTIVE' in mininet/ns3.py, so I ran following commands in ns-3 directory and succeeded to build the patched ns-3.
```
./waf --apiscan=wifi
./waf build
```
8) I tried to run wifiroaming.py by following commands, but host unreachable problem occurs during running the python program.
```
sudo ./waf --pyrun ../../mininet/examples/wifiroaming.py
```

Did you experience any similiar problem while you testing wifiroaming.py?
Can you let me know which files/source codes that I should check? or any possible causes?

This is the download link of ns3 xml file, pcap files and stdout log file from running wifiroaming.py.
https://www.dropbox.com/s/tdphc69mzkg8m79/OpenNet_wifiroaming.zip?dl=0

**Comment by visenchou** [comment]
I also go to the last part , but  it shows that 
*** Adding controller
Traceback (most recent call last):
  File "../../../mininet/examples/wifiroaming.py", line 154, in <module>
    WifiNet()
  File "../../../mininet/examples/wifiroaming.py", line 119, in WifiNet
    tb = addfunc (node, wichannel, wissid)
  File "build/bdist.linux-i686/egg/mininet/ns3.py", line 491, in addSta
    
  File "build/bdist.linux-i686/egg/mininet/ns3.py", line 446, in add
    
TypeError: unbound method intfName() must be called with Link instance as first argument (got Host instance instead)
Command ['/usr/bin/python', '../../../mininet/examples/wifiroaming.py'] exited with code 1

could you do me a favor ?   thank you !
