### ISSUE TITLE
use hping3 to send data to APs in separate terminals with xterm

### ISSUE THREAD

**Issue by matrix69** [dlinknctu/OpenNet#71]
Hi, 
I need APs to ping each other with hping3 simultaneously so I need to do it through xterms.
after running wifiroaming, when I used "s1 hping3 s2" it worked fine, but when I opened an xterm for s1 and then used "hping3 s2" it returned "unable to resolve 's2' ".
I need some simultaneous data sending so I need to open xterm for different APs and  run hping3 in all of them simultaneously.
I also try to assign IP to APs but it didn't work.
can you please suggest a way to identify APs in separate terminals? or any thing that help me with this problem?

Thank you very much

**Comment by kansokusha** [comment]
Hi, matrix69.

Because Mininet CLI automatically substitutes IP addresses for node names.
But xterm does not convert the node names into IP addresses.
Maybe "hping3 S2-IP-ADDRESS" can work in your scenario.

By the way, happy new year.

**Comment by matrix69** [comment]
Hi,
thanks a lot, happy new year to you too, I wish many success for you in 2016 :)

thanks for the response. it seems that  "hping3 S2-IP-ADDRESS" is working I just have one more question, it doesn't matter which AP name or IP I use it works fine with all of them and in all cases it reply ip=92.242.140.21. netanim did not help me in identifying the receiver, so I am not sure how to determine the correct IP address to use as receiver of hping3 files. can you please suggest a way to determine and specify the receiver AP?

thank you very much

**Comment by kansokusha** [comment]
The following example may help you to get some idea.

Script: wifiroaming.py
Controller: \# ryu-manager --verbose --observe-links ryu.app.simple_switch

opennet> sh ip addr add 10.10.10.3/24 dev 's1'
opennet> sh ip addr add 10.10.10.4/24 dev 's2'
opennet> s1 hping3 -c 1 s2
HPING 127.0.0.1 (lo 127.0.0.1): NO FLAGS are set, 40 headers + 0 data bytes
len=40 ip=127.0.0.1 ttl=64 DF id=47696 sport=0 flags=RA seq=0 win=0 rtt=1.6 ms

opennet> s1 hping3 -c 1 10.10.10.4
HPING 10.10.10.4 (lo 10.10.10.4): NO FLAGS are set, 40 headers + 0 data bytes
len=40 ip=10.10.10.4 ttl=64 DF id=2299 sport=0 flags=RA seq=0 win=0 rtt=0.2 ms

opennet> s1 xterm
(xterm)\# hping3 -c 1 10.10.10.4
HPING 10.10.10.4 (lo 10.10.10.4): NO FLAGS are set, 40 headers + 0 data bytes
len=40 ip=10.10.10.4 ttl=64 DF id=2593 sport=0 flags=RA seq=0 win=0 rtt=3.6 ms

**Comment by matrix69** [comment]
That help me a lot, I really appreciate your help.
Thank you very much for your time and assistance.
