### ISSUE TITLE
Is there any way that I can use two controllers in OpenNet?

### ISSUE THREAD

**Issue by matrix69** [dlinknctu/OpenNet#79]
Hi,
I have a network and I want to check its behaviour while two controllers are connected to the network.
Is it possible to have two controllers that control the same network simultaneously?
How can I do this?

thank you very much

**Comment by kansokusha** [comment]
It is possible to deploy multiple controllers in a software-defined network.
But the behaviour of that network depends on which controllers and switches are used.

In the OpenNet, we use Mininet to emulate the software-defined network.
Please refer the following links for more information:
Mininet FAQ: [multiple controllers] (https://github.com/mininet/mininet/wiki/FAQ#multiple-controllers)
OpenFlow Switch Spec [1.5.0](https://www.opennetworking.org/images/stories/downloads/sdn-resources/onf-specifications/openflow/openflow-switch-v1.5.0.noipr.pdf), Chapter 6.3.6
