### ISSUE TITLE
How to re-patch OpenNet?

### ISSUE THREAD

**Issue by kuljaree** [dlinknctu/OpenNet#82]
Hi, 
I want to edit "ns.py" file of OpenNet because I want to call my class in NS3.
Now in my NS3 core have my class. 

Can someone suggest me how to re-patch or recompile OpenNet in this case?

Thanks,

**Comment by kansokusha** [comment]
In the NS-3 directory, use following commands to make your customized class can trigger Python binding and be installed into system library.
 
    ./waf --apiscan=core
    ./waf build
    ./waf install

Then, change the working directory to Mininet, modify your ns3.py and install Mininet again.

    ./util/install.sh -n

After update NS-3 python interface and ns3.py, your customized class should work in the simulation script.

Additional reference:
[Python Bindings in NS-3] (https://www.nsnam.org/wiki/Python_bindings)

**Comment by kuljaree** [comment]
Thank you very much for your response,  Kansokusha.
