### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by lHernan** [dlinknctu/OpenNet#85]
I am trying to install OpenNet and i get this error 
![capturar](https://cloud.githubusercontent.com/assets/6953136/14617449/a9191084-0584-11e6-9836-e306815adfe2.PNG)

any suggestion? 
Thank you in advance,
Hernan.

**Comment by kansokusha** [comment]
Please give your Ubuntu more RAM (e.g. 2 GB).
Remove the current OpenNet directory and try again.

**Comment by lHernan** [comment]
That was the problem thanks! solved!
