### ISSUE TITLE
No module named Netanim [wifiroaming.py]

### ISSUE THREAD

**Issue by iagolmedeiros** [dlinknctu/OpenNet#90]
Hi. I am having some troubles regarding OpenNet codes. Everytime I try to run wifiroaming.py, the following error occurs: "no module named Netanim", even though I know Netanim is running just fine. How can I fix this?

![enviargithub](https://cloud.githubusercontent.com/assets/4355162/15428346/2f2cf0fa-1e71-11e6-9a8b-36c75b7bfc53.png)

P.S.: I don't have any trouble when running these [examples](https://github.com/mininet/mininet/wiki/Link-modeling-using-ns-3)

**Comment by iagolmedeiros** [comment]
More info... no netanim.so

![enviargithub2](https://cloud.githubusercontent.com/assets/4355162/15429592/f87e21bc-1e77-11e6-9814-c8666d281a32.png)

**Comment by kansokusha** [comment]
Hi, could you try our current master branch?
Without a complete OpenNet environment, the example scripts cannot work properly.

Or you can just remove the following lines in the script: L28, L30, L170-L186.
By the way, wifiroaming.py requires an SDN controller to handle the packet forwarding.
