### ISSUE TITLE
AttributeError: 'Mininet' object has no attribute 'addAp'

### ISSUE THREAD

**Issue by caiqiqi** [dlinknctu/OpenNet#94]
Hello,
    When I run the script 'ap-sta-switch-host.py' , I noticed that the Mininet object doesnt have a method called 'addAp'.
  <img width="663" alt="2016-07-03 8 57 50" src="https://cloud.githubusercontent.com/assets/8278315/16545604/8f1455f8-4162-11e6-9cf8-68d938670b26.png">
  As the name suggests, does this method try to add an AP to the mininet topo? But I searched in the source code [net.py](https://github.com/mininet/mininet/blob/master/mininet/net.py) and failed to find the 'addAp' method. Oh, I finally find a repo by your group [net.py](https://github.com/dlinknctu/mininet/blob/opennet/mininet/net.py) But do I need to install this fork of mininet?
    Im currently doing some research. But I got stuck just at the beginning of building custom topos. Appreciate it that you open-sourced this repo. Really looking forward to you reply!
Thanks,

**Comment by kansokusha** [comment]
Yes, addAp () means add an AP in the emulation topology.
The method, addAp (), is identical with addSwitch ().
We may remove addAp () & addSta () in future release.

OpenNet uses a customized version of Mininet.
Without complete installation, OpenNet can not provide the environment of wireless emulation.
