### ISSUE TITLE
propagation models

### ISSUE THREAD

**Issue by akhila-rao** [dlinknctu/OpenNet#95]
Hi,

I would like to use (and modify) the propagation model used for the wifi links in OpenNet. From what I have gathered, the ns3.py file has the function definitions to access ns3 classes. I see that functions to access mobility related classes have been defined in ns3.py. I, however, could not find anything to set or modify the propagation model in this ns3.py file. I hence added some functionality into the ns3.py file for this purpose. How do I now bind these changes to OpenNet. I suppose I need to do some kind of build to add these changes into the byte code. How do I do this ?

Thank you.

**Comment by kansokusha** [comment]
OpenNet uses NS-3 to model the propagation media, while NS-3 uses channel to represent propagation media. In ns3.py, you can find that the script uses ns.wifi.YansWifiChannelHelper to create the Wi-Fi channel.

After you made modification on ns3.py, just run "./install.sh -n" under mininet/util to build mininet.

By the way, [Piotr Jurkiewicz] (https://github.com/piotrjurkiewicz) owns the original credit of ns3.py.
Most of methods and classed are created by Piotr Jurkiewicz, except WifiSegment, which is implemented by OpenNet.
